import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from '@/components/providers/theme-provider';
import NextTopLoader from 'nextjs-toploader';
import PageTransition from '@/components/layouts/page-transition';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader 
            showSpinner={false}
          />
          <PageTransition>
            {children}
            <Toaster />
          </PageTransition>
        </ThemeProvider>
      </body>
    </html>
  );
}
