import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from '@/components/providers/theme-provider';
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader 
            showSpinner={false}
          />
          <main className="flex min-h-screen flex-col items-center justify-center relative overflow-hidden mx-auto">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
